// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAplicado.DAL;

#nullable disable

namespace ProyectoAplicado.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241015234555_AddNewTables")]
    partial class AddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProyectoAplicado.Models.Bebidas", b =>
                {
                    b.Property<int>("BebidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BebidaId");

                    b.ToTable("Bebidas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Cocineros", b =>
                {
                    b.Property<int>("CocineroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CocineroId");

                    b.ToTable("Cocineros");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Comanda", b =>
                {
                    b.Property<int>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CocineroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeseraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComandaId");

                    b.HasIndex("CocineroId");

                    b.HasIndex("MesaId");

                    b.HasIndex("MeseraId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Comidas", b =>
                {
                    b.Property<int>("ComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ComidaId");

                    b.HasIndex("ComandaId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MeseraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("MesaId");

                    b.HasIndex("MeseraId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Mesera", b =>
                {
                    b.Property<int>("MeseraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MeseraId");

                    b.ToTable("meseras");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Comanda", b =>
                {
                    b.HasOne("ProyectoAplicado.Models.Cocineros", "Cocinero")
                        .WithMany()
                        .HasForeignKey("CocineroId");

                    b.HasOne("ProyectoAplicado.Models.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAplicado.Models.Mesera", "Mesera")
                        .WithMany("Comandas")
                        .HasForeignKey("MeseraId");

                    b.Navigation("Cocinero");

                    b.Navigation("Mesa");

                    b.Navigation("Mesera");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Comidas", b =>
                {
                    b.HasOne("ProyectoAplicado.Models.Comanda", null)
                        .WithMany("Comidas")
                        .HasForeignKey("ComandaId");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Mesa", b =>
                {
                    b.HasOne("ProyectoAplicado.Models.Mesera", "Mesera")
                        .WithMany("Mesas")
                        .HasForeignKey("MeseraId");

                    b.Navigation("Mesera");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Comanda", b =>
                {
                    b.Navigation("Comidas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("ProyectoAplicado.Models.Mesera", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
